#ifndef COLORS_H_
#define COLORS_H_

/**
 * http://en.wikipedia.org/wiki/Web_colors
 * $ cat colors.txt | awk '{print "#define COLOR_"$1"\t\"#"$2""$3""$4"\""}' > colors1.txt
 */

#define COLOR_IndianRed	"#CD5C5C"
#define COLOR_LightCoral	"#F08080"
#define COLOR_Salmon	"#FA8072"
#define COLOR_DarkSalmon	"#E9967A"
#define COLOR_LightSalmon	"#FFA07A"
#define COLOR_Crimson	"#DC143C"
#define COLOR_Red	"#FF0000"
#define COLOR_FireBrick	"#B22222"
#define COLOR_DarkRed	"#8B0000"
#define COLOR_Pink	"#FFC0CB"
#define COLOR_LightPink	"#FFB6C1"
#define COLOR_HotPink	"#FF69B4"
#define COLOR_DeepPink	"#FF1493"
#define COLOR_MediumVioletRed	"#C71585"
#define COLOR_PaleVioletRed	"#DB7093"
#define COLOR_LightSalmon	"#FFA07A"
#define COLOR_Coral	"#FF7F50"
#define COLOR_Tomato	"#FF6347"
#define COLOR_OrangeRed	"#FF4500"
#define COLOR_DarkOrange	"#FF8C00"
#define COLOR_Orange	"#FFA500"
#define COLOR_Gold	"#FFD700"
#define COLOR_Yellow	"#FFFF00"
#define COLOR_LightYellow	"#FFFFE0"
#define COLOR_LemonChiffon	"#FFFACD"
#define COLOR_LightGoldenrodYellow	"#FAFAD2"
#define COLOR_PapayaWhip	"#FFEFD5"
#define COLOR_Moccasin	"#FFE4B5"
#define COLOR_PeachPuff	"#FFDAB9"
#define COLOR_PaleGoldenrod	"#EEE8AA"
#define COLOR_Khaki	"#F0E68C"
#define COLOR_DarkKhaki	"#BDB76B"
#define COLOR_Lavender	"#E6E6FA"
#define COLOR_Thistle	"#D8BFD8"
#define COLOR_Plum	"#DDA0DD"
#define COLOR_Violet	"#EE82EE"
#define COLOR_Orchid	"#DA70D6"
#define COLOR_Fuchsia	"#FF00FF"
#define COLOR_Magenta	"#FF00FF"
#define COLOR_MediumOrchid	"#BA55D3"
#define COLOR_MediumPurple	"#9370DB"
#define COLOR_Amethyst	"#9966CC"
#define COLOR_BlueViolet	"#8A2BE2"
#define COLOR_DarkViolet	"#9400D3"
#define COLOR_DarkOrchid	"#9932CC"
#define COLOR_DarkMagenta	"#8B008B"
#define COLOR_Purple	"#800080"
#define COLOR_Indigo	"#4B0082"
#define COLOR_SlateBlue	"#6A5ACD"
#define COLOR_DarkSlateBlue	"#483D8B"
#define COLOR_MediumSlateBlue	"#7B68EE"
#define COLOR_GreenYellow	"#ADFF2F"
#define COLOR_Chartreuse	"#7FFF00"
#define COLOR_LawnGreen	"#7CFC00"
#define COLOR_Lime	"#00FF00"
#define COLOR_LimeGreen	"#32CD32"
#define COLOR_PaleGreen	"#98FB98"
#define COLOR_LightGreen	"#90EE90"
#define COLOR_MediumSpringGreen	"#00FA9A"
#define COLOR_SpringGreen	"#00FF7F"
#define COLOR_MediumSeaGreen	"#3CB371"
#define COLOR_SeaGreen	"#2E8B57"
#define COLOR_ForestGreen	"#228B22"
#define COLOR_Green	"#008000"
#define COLOR_DarkGreen	"#006400"
#define COLOR_YellowGreen	"#9ACD32"
#define COLOR_OliveDrab	"#6B8E23"
#define COLOR_Olive	"#808000"
#define COLOR_DarkOliveGreen	"#556B2F"
#define COLOR_MediumAquamarine	"#66CDAA"
#define COLOR_DarkSeaGreen	"#8FBC8F"
#define COLOR_LightSeaGreen	"#20B2AA"
#define COLOR_DarkCyan	"#008B8B"
#define COLOR_Teal	"#008080"
#define COLOR_Aqua	"#00FFFF"
#define COLOR_Cyan	"#00FFFF"
#define COLOR_LightCyan	"#E0FFFF"
#define COLOR_PaleTurquoise	"#AFEEEE"
#define COLOR_Aquamarine	"#7FFFD4"
#define COLOR_Turquoise	"#40E0D0"
#define COLOR_MediumTurquoise	"#48D1CC"
#define COLOR_DarkTurquoise	"#00CED1"
#define COLOR_CadetBlue	"#5F9EA0"
#define COLOR_SteelBlue	"#4682B4"
#define COLOR_LightSteelBlue	"#B0C4DE"
#define COLOR_PowderBlue	"#B0E0E6"
#define COLOR_LightBlue	"#ADD8E6"
#define COLOR_SkyBlue	"#87CEEB"
#define COLOR_LightSkyBlue	"#87CEFA"
#define COLOR_DeepSkyBlue	"#00BFFF"
#define COLOR_DodgerBlue	"#1E90FF"
#define COLOR_CornflowerBlue	"#6495ED"
#define COLOR_MediumSlateBlue	"#7B68EE"
#define COLOR_RoyalBlue	"#4169E1"
#define COLOR_Blue	"#0000FF"
#define COLOR_MediumBlue	"#0000CD"
#define COLOR_DarkBlue	"#00008B"
#define COLOR_Navy	"#000080"
#define COLOR_MidnightBlue	"#191970"
#define COLOR_Cornsilk	"#FFF8DC"
#define COLOR_BlanchedAlmond	"#FFEBCD"
#define COLOR_Bisque	"#FFE4C4"
#define COLOR_NavajoWhite	"#FFDEAD"
#define COLOR_Wheat	"#F5DEB3"
#define COLOR_BurlyWood	"#DEB887"
#define COLOR_Tan	"#D2B48C"
#define COLOR_RosyBrown	"#BC8F8F"
#define COLOR_SandyBrown	"#F4A460"
#define COLOR_Goldenrod	"#DAA520"
#define COLOR_DarkGoldenrod	"#B8860B"
#define COLOR_Peru	"#CD853F"
#define COLOR_Chocolate	"#D2691E"
#define COLOR_SaddleBrown	"#8B4513"
#define COLOR_Sienna	"#A0522D"
#define COLOR_Brown	"#A52A2A"
#define COLOR_Maroon	"#800000"
#define COLOR_White	"#FFFFFF"
#define COLOR_Snow	"#FFFAFA"
#define COLOR_Honeydew	"#F0FFF0"
#define COLOR_MintCream	"#F5FFFA"
#define COLOR_Azure	"#F0FFFF"
#define COLOR_AliceBlue	"#F0F8FF"
#define COLOR_GhostWhite	"#F8F8FF"
#define COLOR_WhiteSmoke	"#F5F5F5"
#define COLOR_Seashell	"#FFF5EE"
#define COLOR_Beige	"#F5F5DC"
#define COLOR_OldLace	"#FDF5E6"
#define COLOR_FloralWhite	"#FFFAF0"
#define COLOR_Ivory	"#FFFFF0"
#define COLOR_AntiqueWhite	"#FAEBD7"
#define COLOR_Linen	"#FAF0E6"
#define COLOR_LavenderBlush	"#FFF0F5"
#define COLOR_MistyRose	"#FFE4E1"
#define COLOR_Gainsboro	"#DCDCDC"
#define COLOR_LightGrey	"#D3D3D3"
#define COLOR_Silver	"#C0C0C0"
#define COLOR_DarkGray	"#A9A9A9"
#define COLOR_Gray	"#808080"
#define COLOR_DimGray	"#696969"
#define COLOR_LightSlateGray	"#778899"
#define COLOR_SlateGray	"#708090"
#define COLOR_DarkSlateGray	"#2F4F4F"
#define COLOR_Black	"#000000"

/* Base 16-colors */
enum {
	ID_COLOR_Aqua, ID_COLOR_Gray, ID_COLOR_Navy, ID_COLOR_Silver,
	ID_COLOR_Black, ID_COLOR_Green, ID_COLOR_Olive, ID_COLOR_Teal,
	ID_COLOR_Blue, ID_COLOR_Lime, ID_COLOR_Purple, ID_COLOR_White,
	ID_COLOR_Fuchsia, ID_COLOR_Maroon, ID_COLOR_Red, ID_COLOR_Yellow,
	BASE_COLOR_COUNT
};

#endif /* COLORS_H_ */
